theme = "catppuccin_mocha_transparent"

[editor]
line-number = "relative"
shell = ["pwsh"]
completion-replace = true
bufferline = "multiple"
color-modes = true
default-line-ending = "lf"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-s = ":w"
[keys.insert]
C-s = ["normal_mode", "commit_undo_checkpoint", ":write"] 
